package semverparams

/*
This code was generated by mkparamfilefunc
with parameters:
command line:2: -group semver-checks


DO NOT EDIT
*/

import (
	"path/filepath"

	"github.com/nickwells/filecheck.mod/filecheck"
	"github.com/nickwells/param.mod/v3/param"
	"github.com/nickwells/xdg.mod/xdg"
)

// SetGroupConfigFile_semver_checks
// will add a config file to the set which the param
// parser will process before checking the command line
// parameters. This function is one of a pair which will
// define the global and personal config files. It is
// generally best practice to add the global config file
// before adding the personal one. This is so that any
// system-wide defaults can be overriden by personal
// choice. This order also allows any parameters which
// can only be set once to be set in the global config
// file.
func SetGroupConfigFile_semver_checks(ps *param.PSet) error {
	baseDir := xdg.ConfigHome()

	ps.AddGroupConfigFile("semver-checks",
		filepath.Join(baseDir,
			"github.com",
			"nickwells",
			"semverparams.mod",
			"v3",
			"semverparams",
			"group-semver-checks.cfg"),
		filecheck.Optional)
	return nil
}

// SetGroupGlobalConfigFile_semver_checks
// will add a config file to the set which the param
// parser will process before checking the command line
// parameters. This function is one of a pair which will
// define the global and personal config files. It is
// generally best practice to add the global config file
// before adding the personal one. This is so that any
// system-wide defaults can be overriden by personal
// choice. This order also allows any parameters which
// can only be set once to be set in the global config
// file.
func SetGroupGlobalConfigFile_semver_checks(ps *param.PSet) error {
	dirs := xdg.ConfigDirs()
	if len(dirs) == 0 {
		return nil
	}
	baseDir := dirs[0]

	ps.AddGroupConfigFile("semver-checks",
		filepath.Join(baseDir,
			"github.com",
			"nickwells",
			"semverparams.mod",
			"v3",
			"semverparams",
			"group-semver-checks.cfg"),
		filecheck.Optional)
	return nil
}

